---
# vars file for revoke_client

# Service vars
ansible_python_interpreter: /usr/bin/env python3

# Filenames
crl_pem: crl.pem

# Local path
local_easyrsa_path: '{{ playbook_dir }}/../Easy_RSA'
local_pki_path: '{{ local_easyrsa_path }}/ca/pki'

# Server path
server_openvpn_path: /etc/openvpn/
server_easyrsa_path: '{{ ansible_user_dir }}/easyrsa'
server_pki_path: '{{ server_easyrsa_path }}/pki'
