---
galaxy_info:
  author: Grell Gragham
  description: Create OpenVPN config via dockerized EasyRSA
  license: license (BSD)
  min_ansible_version: 2.1
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
