---
# tasks file for revoke_client

- name: Get local username
  local_action: command whoami
  register: local_username
  changed_when: false

- name: Get local user ID
  local_action: command id -u {{ local_username.stdout }}
  register: local_userid
  changed_when: false

- name: Set local username and UID as facts
  set_fact:
    local_username: '{{ local_username.stdout }}'
    local_userid: '{{ local_userid.stdout }}'

- name: Build Easy RSA docker container
  local_action:
    module: docker_image
    name: easyrsa
    tag: easyrsa
    build:
      path: '{{ local_easyrsa_path }}'
      args:
        USERNAME: '{{ local_username }}'
        USERID: '{{ local_userid }}'
    source: local

- name: Revoke client certificate
  local_action:
    module: docker_container
    name: easyrsa
    image: easyrsa:easyrsa
    volumes:
      - '{{ local_easyrsa_path }}/ca:/home/easyrsa/ca'
    env:
      CLIENT_NAME: '{{ client_name }}'
    command: revoke_client

- name: Send CRL to server
  copy:
    src: '{{ local_pki_path }}/{{ crl_pem }}'
    dest: '{{ server_pki_path }}/'

- name: Copy CRL to OpenVPN dir
  become: true
  copy:
    src: '{{ server_pki_path }}/{{ crl_pem }}'
    dest: '{{ server_openvpn_path }}'
    remote_src: true
  notify: Restart OpenVPN
