---
# tasks file for revoke_client

- name: Build Easy RSA docker container
  local_action:
    module: docker_image
    name: easyrsa
    tag: easyrsa
    build:
      path: '{{ local_easyrsa_path }}'
    source: local

- name: Revoke client certificate
  local_action:
    module: docker_container
    name: easyrsa
    image: easyrsa:easyrsa
    volumes:
      - '{{ local_easyrsa_path }}/ca:/home/easyrsa/ca'
    env:
      CLIENT_NAME: '{{ client_name }}'
    command: revoke_client

- name: Send CRL to server
  copy:
    src: '{{ local_pki_path }}/{{ crl_pem }}'
    dest: '{{ server_pki_path }}/'

- name: Copy CRL to OpenVPN dir
  become: true
  copy:
    src: '{{ server_pki_path }}/{{ crl_pem }}'
    dest: '{{ server_openvpn_path }}'
    remote_src: true
  notify: Restart OpenVPN
