---
# vars file for openvpn_deploy

ansible_python_interpreter: /usr/bin/env python3

server_name: ovpn_srv
server_easyrsa_path: '{{ ansible_user_dir }}/easyrsa'
local_easyrsa_path: ../Easy_RSA/ca
server_pki_path: '{{ server_easyrsa_path }}/pki'
local_pki_path: ../Easy_RSA/ca/pki
server_req_source: '{{ server_pki_path }}/reqs/{{ server_name }}.req'
server_req_dest: '{{ local_pki_path }}/reqs/'
server_cert_source: '{{ local_pki_path }}/issued/{{ server_name }}.crt'
server_cert_dest: '{{ server_pki_path }}/issued/'
server_cert_path: '{{ server_pki_path }}/issued'
server_key_path: '{{ server_pki_path }}/private'
local_ca_cert_source: '{{ local_pki_path }}/ca.crt'

easyrsa_docker_path: ../Easy_RSA

server_openvpn_path: /etc/openvpn
